# Testing Functions

In [137]:
import pandas as pd

In [138]:
data = pd.read_csv("exam_results_raw.csv")

In [139]:
data.head()

,student_id,school_code,subject,governorate,score,studied_hours,pass_fail
0,1089,SCH002,Science,Alexandria,62.600000,NaN,Pass
1,1086,SCH004,Science,Luxor,71.315907,4.0,Pass
2,1004,SCH003,Math,Aswan,58.000000,8.2,Pass
3,1087,SCH005,Arabic,Cairo,64.700000,8.3,Pass
4,1057,SCH003,Science,Aswan,81.305910,NaN,Pass

In [ ]:
data["studied_hours"].unique()

array([ nan,  4. ,  8.2,  8.3,  5.4,  6.1,  2.4,  2.2,  6.7,  7.5,  5.6,
        3.7,  6.5,  9.2,  7.1,  4.1,  4.7,  3.6,  5.1,  2.3,  4.6,  5.7,
        4.9,  1.9,  6. ,  2.8,  7.4,  5.3,  5.8,  5.9,  3.4,  7.2,  8. ,
        3. ,  6.8,  8.5,  7.3,  4.8, 10. ,  8.4,  6.2,  8.1,  2.5,  4.4,
        2.7,  9.8,  1.3,  2.6,  6.9,  5.5,  9.9,  4.3,  5. ,  9.6,  1.8,
        5.2,  7. ,  3.9,  6.3,  3.8,  1.7,  3.2,  1.6,  3.1,  3.5,  3.3,
        7.7,  1. ,  4.2,  9.3, -0.7,  4.5,  7.8,  2.9,  2.1,  1.5,  0.7,
        6.4, -0.8, 10.2,  9.4,  8.8,  7.6,  0. ,  9.5])

In [141]:
data.describe()

        student_id       score  studied_hours
count   318.000000  298.000000     306.000000
mean   1048.710692   74.327657       5.170588
std      29.815594   57.991554       2.079230
min    1000.000000  -50.000000      -0.800000
25%    1023.000000   63.125000       3.700000
50%    1051.000000   71.950000       5.200000
75%    1073.750000   78.400000       6.500000
max    1099.000000  999.000000      10.200000

In [142]:
data.duplicated().sum()

np.int64(10)

In [143]:
def duplicates_sentizer():
    global data
    if data.duplicated().sum() != 0 :  
       data = data.drop_duplicates().copy()
    return data.duplicated().sum()

In [144]:
duplicates_sentizer()

np.int64(0)

In [145]:
def outliers_sentizer():
    
    q1 = pd.Series(sorted(data["studied_hours"])).quantile(0.25)
    q3 = pd.Series(sorted(data["studied_hours"])).quantile(0.75)
    IQR = q3-q1
    upper_fence = q3 + 1.5 * IQR
    lower_fence = q1 + 1.5 * IQR
    data["studied_hours"] = data["studied_hours"].clip(lower_fence , upper_fence)

In [146]:
outliers_sentizer()

In [147]:
def nulls_sentizer(): 
       
    if data["studied_hours"].isna().sum() != 0 : 
        data["studied_hours"] = data["studied_hours"].fillna(data["studied_hours"].mean())
    return data.isna().sum()

In [148]:
nulls_sentizer()

student_id        0
school_code       0
subject           0
governorate       0
score            20
studied_hours     0
pass_fail        15
dtype: int64

In [149]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 308 entries, 0 to 317
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     308 non-null    int64
 1   school_code    308 non-null    object
 2   subject        308 non-null    object
 3   governorate    308 non-null    object
 4   score          288 non-null    float64
 5   studied_hours  308 non-null    float64
 6   pass_fail      293 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 14.4+ KB

In [150]:
data.describe()

        student_id       score  studied_hours
count   308.000000  288.000000     308.000000
mean   1048.850649   74.898062       7.990572
std      29.962579   58.689104       0.343358
min    1000.000000  -50.000000       7.900000
25%    1022.750000   63.300000       7.900000
50%    1051.000000   72.100000       7.900000
75%    1074.000000   78.600000       7.900000
max    1099.000000  999.000000      10.200000

In [151]:
def ROP ():

<class '_IncompleteInputError'>: incomplete input (<ipython-input-151-b11e535550b8>, line 2)

In [155]:
targted_sales = data.loc[data["student_id"] == 1089 ]
targted_sales

,student_id,school_code,subject,governorate,score,studied_hours,pass_fail
0,1089,SCH002,Science,Alexandria,62.6,7.990572,Pass
8,1089,SCH005,English,Cairo,NaN,7.900000,Pass
28,1089,SCH001,Science,Alexandria,75.2,7.900000,Pass
140,1089,SCH002,Science,Aswan,77.7,7.900000,Pass
177,1089,SCH005,Math,Alexandria,62.2,7.900000,Pass
275,1089,SCH001,Science,Cairo,-50.0,7.900000,Pass
307,1089,SCH001,Math,Giza,63.4,7.900000,Pass

In [153]:
   data["studied_hours"].unique()

array([ 7.99057239,  7.9       ,  8.2       ,  8.3       ,  9.2       ,
        8.        ,  8.5       , 10.        ,  8.4       ,  8.1       ,
        9.8       ,  9.9       ,  9.6       ,  9.3       , 10.2       ,
        9.4       ,  8.8       ,  9.5       ])

In [178]:
def ROP ():
    global avg_sales
    global lead_time
    global _max_lead_time
    global _avg_lead_time
    lead_time = int(input("Please Enter the lead time of the product: "))
    _max_lead_time = int(input("Please Enter the Maximum lead time of the product: "))
    _avg_lead_time = int(input("Please Enter the Average lead time of the product: "))
    avg_sales = data["studied_hours"].mean()
    safety_stock =(max(data["studied_hours"]) * 10) - (avg_sales * 6)
    rop = (avg_sales * lead_time) + safety_stock
    return rop

In [179]:
ROP()

Please Enter the lead time of the product:  5
Please Enter the Maximum lead time of the product:  5
Please Enter the Average lead time of the product:  5

np.float64(94.0094276094276)

In [173]:
avg_sales = data["studied_hours"].mean()
lead_time = int(input("Please Enter the lead time of the product: "))

Please Enter the lead time of the product:  5

np.float64(39.952861952861944)

In [1]:
avg_sales * 5

<class 'NameError'>: name 'avg_sales' is not defined

# StockAlert x Sql

In [3]:
%pip install mysql-connector-python

In [4]:
import mysql.connector

In [6]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="NewPassword123"
)

print(mydb)

<class 'mysql.connector.errors.OperationalError'>: 2055: Lost connection to MySQL server at 'localhost:3306', system error: Errno 6: Resource temporarily unavailable